Changing one model's name which was having issues.
Known error: https://github.com/mlfoundations/open_clip/issues/594

Error: https://github.com/marqo-ai/marqo/actions/runs/12275146990/job/34249731062#step:9:1245